specVersion: 0.0.8
schema:
  file: ./schema.graphql
{{#graftEnabled}}
features:
  - grafting
graft:
  base: {{ subgraphId }} # Subgraph ID of base subgraph
  block: {{ graftStartBlock }} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum
    name: Cream
    network: {{ network }}
    source:
      address: "{{ cream.address }}"
      abi: Cream
      startBlock: {{ cream.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - Pool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Protocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
      abis:
        - name: Cream
          file: ./abis/Cream/Cream.json
        - name: CRETH
          file: ./abis/Cream/CRETH.json

        - name: ERC20
          file: ./abis/Tokens/ERC20.json
        - name: _ERC20
          file: ./abis/Tokens/_ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/Tokens/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/Tokens/ERC20NameBytes.json
        - name: ChainlinkDataFeed
          file: ./abis/Tokens/ChainlinkDataFeed.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransferCream
      file: {{{ file }}}
  - kind: ethereum
    name: CRETH
    network: {{ network }}
    source:
      address: "{{ creth.address }}"
      abi: CRETH
      startBlock: {{ creth.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - Pool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Protocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
      abis:
        - name: Cream
          file: ./abis/Cream/Cream.json
        - name: CRETH
          file: ./abis/Cream/CRETH.json

        - name: ERC20
          file: ./abis/Tokens/ERC20.json
        - name: _ERC20
          file: ./abis/Tokens/_ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/Tokens/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/Tokens/ERC20NameBytes.json
        - name: ChainlinkDataFeed
          file: ./abis/Tokens/ChainlinkDataFeed.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransferCreth
      file: {{{ file }}}