specVersion: 0.0.8
schema:
  file: ./schema.graphql
{{#graftEnabled}}
features:
  - grafting
graft:
  base: {{ subgraphId }} # Subgraph ID of base subgraph
  block: {{ graftStartBlock }} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum
    name: STCELO
    network: {{ network }}
    source:
      address: "{{ stcelo.address }}"
      abi: STCELO
      startBlock: {{ stcelo.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - Pool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Protocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
      abis:
        - name: STCELO
          file: ./abis/STCELO/STCELO.json

        - name: ERC20
          file: ./abis/Tokens/ERC20.json
        - name: _ERC20
          file: ./abis/Tokens/_ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/Tokens/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/Tokens/ERC20NameBytes.json
        - name: ChainlinkDataFeed
          file: ./abis/Tokens/ChainlinkDataFeed.json
      eventHandlers:
        - event: VotesScheduled(indexed address,uint256)
          handler: handleVotesScheduled
        - event: CeloWithdrawalScheduled(indexed address,indexed address,uint256)
          handler: handleCeloWithdrawalScheduled
        - event: CeloWithdrawalStarted(indexed address,indexed address,uint256)
          handler: handleCeloWithdrawalStarted
      file: {{{ file }}}