specVersion: 0.0.8
schema:
  file: ./schema.graphql
{{#graftEnabled}}
features:
  - grafting
graft:
  base: {{ subgraphId }} # Subgraph ID of base subgraph
  block: {{ graftStartBlock }} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum
    name: APETH
    network: {{ network }}
    source:
      address: "{{ apETH.address }}"
      abi: APETH
      startBlock: {{ apETH.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - Pool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Protocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
      abis:
        - name: APETH
          file: ./abis/AquaPatina/APETH.json
        - name: APETHEarlyDeposits
          file: ./abis/AquaPatina/APETHEarlyDeposits.json

        - name: ERC20
          file: ./abis/Tokens/ERC20.json
        - name: _ERC20
          file: ./abis/Tokens/_ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/Tokens/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/Tokens/ERC20NameBytes.json
        - name: ChainlinkDataFeed
          file: ./abis/Tokens/ChainlinkDataFeed.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: {{{ file }}}
  - kind: ethereum
    name: APETHEarlyDeposits
    network: {{ network }}
    source:
      address: "{{ apETHEarlyDeposits.address }}"
      abi: APETHEarlyDeposits
      startBlock: {{ apETHEarlyDeposits.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - Pool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Protocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
      abis:
        - name: APETH
          file: ./abis/AquaPatina/APETH.json
        - name: APETHEarlyDeposits
          file: ./abis/AquaPatina/APETHEarlyDeposits.json

        - name: ERC20
          file: ./abis/Tokens/ERC20.json
        - name: _ERC20
          file: ./abis/Tokens/_ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/Tokens/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/Tokens/ERC20NameBytes.json
        - name: ChainlinkDataFeed
          file: ./abis/Tokens/ChainlinkDataFeed.json
      eventHandlers:
        - event: Minted(address,uint256)
          handler: handleMinted
      file: {{{ file }}}
